### ISSUE TITLE
As a Tester,I want to Visualize the Test the functionalites of the signup and login page

### ISSUE THREAD

**Issue by Maruthi158** [Maruthi158/gdpFrontend#2]
**Acceptance Criteria**

1.As a Tester I want to check whether email field is accepted without @ symbol
2.As a Tester I want to validate giving password less than 8 characters is accepting
3.As a tester i want to verify if all the required fields are not filled it is display some error message near the field

**Comment by GUNDAANUTEJ** [comment]
1. As a Tester, I tested whether email field is accepted without @ symbol
2. As a Tester, I validated giving password less than 8 characters is accepting
3. As a tester, I verified if all the required fields are not filled it displayed some error message near the field
